name: Deploy Jekyll site

on:
  push:
    branches:
      - deploy  # Trigger deployment when pushing to the deploy branch

jobs:
  jekyll-build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'  # Adjust this to your Ruby version if needed

      - name: List directory contents
        run: ls -la

      - name: Find Jekyll files
        run: |
          find . -name "_config.yml"
          find . -name "Gemfile"

      - name: Display Jekyll version
        run: jekyll -v

      - name: Install Jekyll
        run: gem install jekyll bundler

      - name: Build Jekyll site
        run: jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site  # Jekyll's default output directory
